# Testing the Package Components

**Author:** Cleverson Matiolli, PhD
**Date:** 2026-07-10

In this notebook, we test the functions of the 'aidweather' package. Since I am a careful person, I want to test each function separetely to make sure it works as expected.

## Tests by Modules:

1. Config Module [`aidweather.config`](./src/aidweather/config.py)
2. Geo Module [`aidweather.geo`](./src/aidweather/geo.py)
3. Client Module [`aidweather.client`](./src/aidweather/client.py)
4. Utils Module [`aidweather.utils`](./src/aidweather/utils.py)

## 1. Config Module

In [1]:
from aidweather import cfg

In [2]:
cfg.api_limits()

{'max_parameters_per_point_request': 20,
 'max_parameters_per_regional_request': 1,
 'max_bbox_degrees': 4.5,
 'recommended_community': 'AG',
 'max_workers': 5,
 'rate_limit_calls': 30,
 'rate_limit_period_seconds': 60}

In [3]:
cfg.get_native_grid(community="AG")

(0.5, 0.625)

In [4]:
cfg.cache_config()

{'enabled': True, 'path': '/home/clever/.cache/aidweather'}

In [5]:
cfg.get_url(temporal_api="daily")

'https://power.larc.nasa.gov/api/temporal/daily/point'

In [6]:
cfg.get_url(temporal_api="hourly")

'https://power.larc.nasa.gov/api/temporal/hourly/point'

In [7]:
cfg.logging_config()

{'enabled': True,
 'filename': '/home/clever/.local/state/aidweather/log/aidweather.log',
 'level': 'INFO'}

In [8]:
cfg.param_descriptions()

{'T2M': 'Average Air Temperature at 2 m (°C): Modeled daily average air temperature. Data is obtained from the NASA MERRA-2 assimilation model (1981-Present, ~0.5°x0.625° resolution). In agriculture, T2M is critical for calculating Growing Degree Days (GDD) and modeling crop developmental stages and growth rates. Used in machine learning models for yield prediction and thermal stress assessment.',
 'T2M_MAX': 'Maximum Air Temperature at 2 m (°C): Modeled maximum hourly air temperature. Data is obtained from the NASA MERRA-2 assimilation model (1981-Present, ~0.5°x0.625° resolution). T2M_MAX is vital for detecting heat stress events which can cause flower abortion, reduced photosynthesis, and poor grain filling. Used as a feature in ML models to flag high-temperature risk periods.',
 'T2M_MIN': 'Minimum Air Temperature at 2 m (°C): Modeled minimum hourly air temperature. Data is obtained from the NASA MERRA-2 assimilation model (1981-Present, ~0.5°x0.625° resolution). T2M_MIN is essential for identifying frost risk (chilling injury) and for calculating GDD base temperatures. Used in phenology models to predict planting/harvest windows.',
 'T2M_RANGE': 'Diurnal Temperature Range at 2 m (°C): The difference between T2M_MAX and T2M_MIN. Data is derived from the NASA MERRA-2 model (1981-Present). A large range can impact evapotranspiration (ET) and plant respiration efficiency. It is used in data science for calculating stress indices and ET estimations.',
 'T2MWET': 'Wet Bulb Temperature at 2 m (°C): The adiabatic saturation temperature (cooling limit by evaporation). Data is obtained from the NASA MERRA-2 model (1981-Present). T2MWET is a measure of combined heat and humidity, highly relevant for assessing potential animal heat stress in livestock operations and for calculating cooling needs in controlled environments.',
 'T2MDEW': 'Dew Point Temperature at 2 m (°C): The temperature at which air becomes saturated and condensation forms. Data is obtained from the NASA MERRA-2 model (1981-Present). This parameter is crucial for predicting conditions conducive to foliar fungal diseases (e.g., rusts, blights) where prolonged leaf wetness is required for spore germination.',
 'TS': 'Surface Skin Temperature (°C): The calculated temperature of the top surface of the Earth (soil, vegetation canopy, or water). Data is obtained from the NASA MERRA-2 model (1981-Present). TS is a key input for remote sensing-based Evapotranspiration (ET) models (e.g., SEBAL/METRIC), and for monitoring soil temperature influence on seed germination and root growth.',
 'RH2M': 'Relative Humidity at 2 m (%): Ratio of actual water vapor content to the maximum possible saturation. Data is obtained from the NASA MERRA-2 model (1981-Present, ~0.5°x0.625° resolution). RH2M affects transpiration rates (low RH increases water loss) and disease incidence. Used in ML models for predicting irrigation needs and disease risk.',
 'PRECTOTCORR': "Corrected Total Precipitation (mm/day): Total liquid and frozen water precipitation, adjusted for known biases. Data is obtained from the NASA MERRA-2 model (1981/1997-Present, ~0.5°x0.625° resolution). Essential for water balance models, irrigation scheduling, and assessing drought/flood risk. It's a primary input feature for deep learning models predicting crop yield.",
 'ALLSKY_SFC_SW_DWN': 'All Sky Surface Shortwave Downward Radiation (kWh/m²/day): Total solar energy reaching the surface under actual atmospheric conditions (Direct + Diffuse). Data is derived from NASA satellite observations (1984-Present, ~1.0°x1.0° resolution). This is the key energy input for calculating Reference Evapotranspiration (ETo) using methods like Penman-Monteith, which drives irrigation decisions.',
 'ALLSKY_SFC_PAR_TOT': 'All Sky Photosynthetically Active Radiation (MJ/m²/day): The total energy flux (400-700 nm) used by plants for photosynthesis. Data is derived from NASA satellite observations (1984-Present, ~1.0°x1.0° resolution). This directly quantifies the light available for plant growth. Used in Crop Growth Models (CGMs) like DSSAT and APSIM to simulate biomass accumulation and final yield.',
 'WS10M': 'Average Wind Speed at 10 m (m/s): Modeled daily average horizontal movement of air. Data is obtained from the NASA MERRA-2 model (1981-Present). Wind is a crucial factor in the Evapotranspiration (ET) calculation and can cause mechanical stress. Used in predictive models for water loss and general crop stress.',
 'WS10M_MAX': 'Maximum Wind Speed at 10 m (m/s): Modeled maximum instantaneous wind speed. Data is obtained from the NASA MERRA-2 model (1981-Present). Essential for assessing potential structural damage to crops (lodging of cereals/maize) or infrastructure (greenhouses). Used as a threshold trigger for high-risk warnings in decision-support systems.',
 'WD10M': 'Average Wind Direction at 10 m (degrees): Modeled daily average direction from which the wind is blowing. Data is obtained from the NASA MERRA-2 model (1981-Present). Primarily used for modeling the drift/dispersion of airborne inputs (pesticides, herbicides, spores) and for local climate pattern analysis (e.g., windbreak planning).',
 'PS': "Surface Pressure (kPa): The atmospheric pressure at the earth's surface, adjusted for local elevation. Data is obtained from the NASA MERRA-2 model (1981-Present). PS is a necessary input for the Penman-Monteith Evapotranspiration equation to accurately account for air density, making it fundamental for precise water management."}

In [9]:
cfg.param_groups()

['all', 'default']

In [10]:
cfg.param_metadata(params=["T2M", "RH2M"])

{'T2M': {'short_name': 'Temperature at 2 Meters',
  'description': 'Average Air Temperature at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'RH2M': {'short_name': 'Relative Humidity at 2 Meters',
  'description': 'Relative Humidity at 2 m',
  'units': {'daily': '%', 'hourly': '%'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'}}

In [11]:
cfg.param_metadata()

{'T2M': {'short_name': 'Temperature at 2 Meters',
  'description': 'Average Air Temperature at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'T2M_MAX': {'short_name': 'Maximum Temperature at 2 Meters',
  'description': 'Maximum Air Temperature at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'T2M_MIN': {'short_name': 'Minimum Temperature at 2 Meters',
  'description': 'Minimum Air Temperature at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'T2M_RANGE': {'short_name': 'Temperature Range at 2 Meters',
  'description': 'Diurnal Temperature Range at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'T2MWET': {'short_name': 'Wet Bulb Temperature at 2 Meters',
  'description': 'Wet Bulb Temperature at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'T2MDEW': {'short_name': 'Dew Point Temperature at 2 Meters',
  'description': 'Dew Point Temperature at 2 m',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'TS': {'short_name': 'Surface Skin Temperature',
  'description': 'Surface Skin Temperature',
  'units': {'daily': '°C', 'hourly': '°C'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'RH2M': {'short_name': 'Relative Humidity at 2 Meters',
  'description': 'Relative Humidity at 2 m',
  'units': {'daily': '%', 'hourly': '%'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'PRECTOTCORR': {'short_name': 'Corrected Total Precipitation',
  'description': 'Corrected Total Precipitation (liquid + ice)',
  'units': {'daily': 'mm/day', 'hourly': 'mm/hr'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'ALLSKY_SFC_SW_DWN': {'short_name': 'All Sky Surface Shortwave Downward Irradiance',
  'description': 'All Sky Surface Shortwave Downward Radiation',
  'units': {'daily': 'kWh/m²/day', 'hourly': 'W/m²'},
  'source_family': 'CERES SYN1deg / FLASHFlux / SRB',
  'native_grid': {'latitude_degrees': 1.0, 'longitude_degrees': 1.0},
  'availability': {'daily_start': '1984-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / LaRC CERES'},
 'ALLSKY_SFC_PAR_TOT': {'short_name': 'All Sky Surface PAR Total',
  'description': 'All Sky Photosynthetically Active Radiation',
  'units': {'daily': 'MJ/m²/day', 'hourly': 'W/m²'},
  'source_family': 'CERES SYN1deg / FLASHFlux / SRB',
  'native_grid': {'latitude_degrees': 1.0, 'longitude_degrees': 1.0},
  'availability': {'daily_start': '1984-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / LaRC CERES'},
 'WS10M': {'short_name': 'Wind Speed at 10 Meters',
  'description': 'Average Wind Speed at 10 m',
  'units': {'daily': 'm/s', 'hourly': 'm/s'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'WS10M_MAX': {'short_name': 'Maximum Wind Speed at 10 Meters',
  'description': 'Maximum Wind Speed at 10 m',
  'units': {'daily': 'm/s', 'hourly': 'm/s'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'WD10M': {'short_name': 'Wind Direction at 10 Meters',
  'description': 'Average Wind Direction at 10 m',
  'units': {'daily': 'degrees', 'hourly': 'degrees'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'},
 'PS': {'short_name': 'Surface Pressure',
  'description': 'Surface Pressure',
  'units': {'daily': 'kPa', 'hourly': 'kPa'},
  'source_family': 'MERRA-2/GEOS-IT',
  'native_grid': {'latitude_degrees': 0.5, 'longitude_degrees': 0.625},
  'availability': {'daily_start': '1981-01-01', 'hourly_start': '2001-01-01'},
  'time_standards': ['LST', 'UTC'],
  'provisional_tail': True,
  'attribution': 'NASA POWER / GMAO MERRA-2'}}

## 2. Geo Module

In [12]:
from aidweather import GeoCoordinate, normalize_coord_input

In [13]:
coord = GeoCoordinate.from_decimal(-23.55, -46.633333)
print(coord)

GeoCoordinate(lat=-23.55, lon=-46.633333)

In [14]:
coord1 = GeoCoordinate.from_strings("23° 33' 00\" S", "46° 37' 59.88\" W")
coord2 = GeoCoordinate.from_strings("23° 33.0' S", "46° 37.998' W")
coord3 = GeoCoordinate.from_strings("23.55° S", "46.6333° W")

print(coord1)
print(coord2)
print(coord3)

GeoCoordinate(lat=-23.55, lon=-46.6333)
GeoCoordinate(lat=-23.55, lon=-46.6333)
GeoCoordinate(lat=-23.55, lon=-46.6333)

In [15]:
coord1 = GeoCoordinate.from_dd_str("23.55° S", "46.6333° W")
coord2 = GeoCoordinate.from_dd_str(
    "-23.55", "-46.6333"
)  # sign-only, no hemisphere letter

print(coord1)
print(coord2)

GeoCoordinate(lat=-23.55, lon=-46.6333)
GeoCoordinate(lat=-23.55, lon=-46.6333)

In [16]:
coord = GeoCoordinate.from_ddm_str("23° 33.0' S", "46° 37.998' W")
print(coord)

GeoCoordinate(lat=-23.55, lon=-46.6333)

In [17]:
coord = GeoCoordinate.from_dms_str("23° 33' 00\" S", "46° 37' 59.88\" W")
print(coord)

GeoCoordinate(lat=-23.55, lon=-46.6333)

In [18]:
coord.as_decimal()

(-23.55, -46.6333)

In [19]:
coord.to_dd()

(-23.55, -46.6333)

In [20]:
coord.to_dd_str()

('23.55000° S', '46.63330° W')

In [21]:
coord.to_dd_str(lat_precision=2, lon_precision=2)

('23.55° S', '46.63° W')

In [22]:
coord.to_ddm_str()

("23°33.000' S", "46°37.998' W")

In [23]:
coord.to_dms_str()

('23°33\'0" S', '46°37\'60" W')

In [24]:
coord.to_dms_str(second_precision=2)

('23°33\'0.00" S', '46°37\'59.88" W')

In [25]:
# All equivalent:
c1 = normalize_coord_input(-23.55, -46.63)
c2 = normalize_coord_input((-23.55, -46.63))
c3 = normalize_coord_input(GeoCoordinate.from_decimal(-23.55, -46.63))
c4 = normalize_coord_input("23.55° S", "46.63° W")
c5 = normalize_coord_input(("23° 33.0' S", "46° 37.8' W"))

for c in [c1, c2, c3, c4, c5]:
    print(c)
assert c1 == c2 == c3 == c4 == c5

GeoCoordinate(lat=-23.55, lon=-46.63)
GeoCoordinate(lat=-23.55, lon=-46.63)
GeoCoordinate(lat=-23.55, lon=-46.63)
GeoCoordinate(lat=-23.55, lon=-46.63)
GeoCoordinate(lat=-23.55, lon=-46.63)

In [26]:
from aidweather.geo import parse_dd

print(parse_dd("23.55° S", is_lat=True))  # -23.55
print(parse_dd("-23.55", is_lat=True))  # -23.55
print(parse_dd("46.63° W", is_lat=False))  # -46.63

-23.55
-23.55
-46.63

In [27]:
from aidweather.geo import parse_ddm

print(parse_ddm("23° 33.0' S", is_lat=True))  # -23.55
print(parse_ddm("46° 37.998' W", is_lat=False))  # -46.6333)

-23.55
-46.6333

In [28]:
from aidweather.geo import parse_dms

print(parse_dms("23° 33' 0\" S", is_lat=True))  # -23.55
print(parse_dms("46° 37' 59.88\" W", is_lat=False))  # -46.6333

-23.55
-46.6333

In [29]:
from aidweather.geo import parse_any_coord_string

print(parse_any_coord_string("23° 33' 0\" S", is_lat=True))  # DMS → -23.55
print(parse_any_coord_string("23° 33.0' S", is_lat=True))  # DDM → -23.55
print(parse_any_coord_string("23.55° S", is_lat=True))  # DD  → -23.55

-23.55
-23.55
-23.55

In [30]:
from aidweather.geo import decimal_to_ddm_components

decimal_to_ddm_components(-23.55, is_lat=True)
# (23, 33.0, 'S')

(23, 33.00000000000004, 'S')

In [31]:
from aidweather.geo import decimal_to_dms_components

print(decimal_to_dms_components(-23.55, is_lat=True))
# (23, 33, 0.0, 'S')

print(decimal_to_dms_components(-46.633333, is_lat=False))
# (46, 37, 59.9988, 'W')

(23, 33, 2.5579538487363607e-12, 'S')
(46, 37, 59.998800000001324, 'W')

## 3. Client Module

In [32]:
from aidweather import PowerClient

# Daily client
daily_client = PowerClient(temporal_api="daily")

# Hourly client
hourly_client = PowerClient(temporal_api="hourly")

daily_client, hourly_client

(<PowerClient(api='daily', url='https://power.larc.nasa.gov/api/temporal/daily/point')>,
 <PowerClient(api='hourly', url='https://power.larc.nasa.gov/api/temporal/hourly/point')>)

In [33]:
from aidweather import GeoCoordinate, PowerClient

client = PowerClient(temporal_api="daily")
coord = GeoCoordinate.from_decimal(-23.55, -46.63)

df = client.get_point_data_from_coordinate(
    coord=coord,
    start="2023-01-01",
    end="2023-01-31",
    params=["T2M", "T2M_MAX", "T2M_MIN", "PRECTOTCORR"],
)

df.head()

              T2M  T2M_MAX  T2M_MIN  PRECTOTCORR
date
2023-01-01  22.35    27.85    17.78         1.85
2023-01-02  22.91    28.17    17.37         1.26
2023-01-03  22.61    26.83    19.17         6.21
2023-01-04  21.36    25.83    17.20        33.93
2023-01-05  18.27    22.29    16.07        11.71

In [34]:
from IPython.core.display_functions import display

points = [
    {"lat": -23.55, "lon": -46.63, "name": "Site_A"},
    {"lat": -22.90, "lon": -43.20, "name": "Site_B"},
]

df_multi, failed = client.get_multi_point_data(
    points=points,
    start="2023-01-01",
    end="2023-01-10",
    params=["T2M"],
    max_workers=5,
)
display(df_multi.head())
failed

        date    T2M   lat   lon    name
0 2023-01-01  24.21 -22.9 -43.2  Site_B
1 2023-01-02  24.70 -22.9 -43.2  Site_B
2 2023-01-03  25.48 -22.9 -43.2  Site_B
3 2023-01-04  25.62 -22.9 -43.2  Site_B
4 2023-01-05  23.54 -22.9 -43.2  Site_B

[]

In [35]:
coord_start = GeoCoordinate.from_decimal(-25.0, -48.0)
coord_end = GeoCoordinate.from_decimal(-20.0, -48.0)

df_transect = client.get_transect_data(
    start_coord=coord_start,
    end_coord=coord_end,
    start="2023-01-01",
    end="2023-01-07",
    params=["T2M", "ALLSKY_SFC_SW_DWN"],
    spacing_km=50.0,
)

print(df_transect["name"].unique())
print(df_transect["lat"].unique())
print(df_transect["lon"].unique())
df_transect.head()

<ArrowStringArray>
[ 'Point_2',  'Point_1',  'Point_3',  'Point_5',  'Point_4',  'Point_6',
  'Point_7',  'Point_8',  'Point_9', 'Point_11', 'Point_10']
Length: 11, dtype: str
[-24.5 -25.  -24.  -23.  -23.5 -22.5 -22.  -21.5 -21.  -20.  -20.5]
[-48.]

        date    T2M  ALLSKY_SFC_SW_DWN   lat   lon     name
0 2023-01-01  23.40              20.22 -24.5 -48.0  Point_2
1 2023-01-02  24.47              24.51 -24.5 -48.0  Point_2
2 2023-01-03  25.95              16.45 -24.5 -48.0  Point_2
3 2023-01-04  21.32               6.83 -24.5 -48.0  Point_2
4 2023-01-05  19.31               8.38 -24.5 -48.0  Point_2

In [36]:
df_regional = client.get_regional_data(
    lat_min=-23.5,
    lat_max=-20.0,
    lon_min=-47.0,
    lon_max=-44.0,
    start="2023-01-01",
    end="2023-01-07",
    params=["T2M"],
)

df_regional.head()

             lat     lon  elevation    T2M
date
2023-01-01 -23.5 -46.875     790.19  22.35
2023-01-01 -23.0 -46.875     755.36  23.12
2023-01-01 -21.0 -45.000     940.40  21.27
2023-01-01 -21.0 -45.625     859.03  22.48
2023-01-01 -20.0 -46.250     917.07  22.44

## 4. Utils Module

In [37]:
import pandas as pd

from aidweather.utils import ensure_date_column

df = pd.DataFrame({"date": ["2023-01-01", "2023-01-02"], "T2M": [22.1, 21.8]})
df = ensure_date_column(df)

print(df.dtypes)
# date    datetime64[ns]
# T2M     float64

date    datetime64[us]
T2M            float64
dtype: object

In [38]:
df = pd.DataFrame({"timestamp": ["2023-01-01", "2023-01-02"], "T2M": [22.1, 21.8]})

# Tell ensure_date_column to look for "timestamp" as a fallback:
df = ensure_date_column(df, candidates=["timestamp", "time", "dt"])

# The result has a "date" column; "timestamp" is dropped.
print(df.columns.tolist())  # ["date", "T2M"]

['T2M', 'date']

In [39]:
# PowerClient returns DataFrames indexed by date:
_ = df.index  # DatetimeIndex(['2023-01-01', '2023-01-02', ...], dtype='datetime64[ns]', name='date')

# ensure_date_column extracts the index into a column:
df = ensure_date_column(df, index_fallback=True)

print(df["date"].dtype)  # datetime64[ns]

datetime64[us]

In [40]:
# Source data has sub-daily timestamps:
df = pd.DataFrame(
    {
        "date": ["2023-01-01 06:00:00", "2023-01-02 18:30:00"],
        "T2M": [22.1, 21.8],
    }
)
df = ensure_date_column(df, normalize=True)

print(df["date"])
# 0   2023-01-01
# 1   2023-01-02

0   2023-01-01
1   2023-01-02
Name: date, dtype: datetime64[us]

In [41]:
# A DataFrame coming from a tz-aware data source:
df = pd.DataFrame(
    {
        "date": pd.to_datetime(["2023-01-01", "2023-01-02"]).tz_localize("UTC"),
        "T2M": [22.1, 21.8],
    }
)

# Default behaviour strips the timezone:
df = ensure_date_column(df)
print(df["date"].dt.tz)  # None

None

In [42]:
from aidweather.utils import DateColumnOptions, ensure_date_column

opts = DateColumnOptions(
    candidates=["timestamp", "time"],
    index_fallback=True,
    normalize=True,
    strip_timezone=True,
)

df = ensure_date_column(
    df, **{f.name: getattr(opts, f.name) for f in opts.__dataclass_fields__.values()}
)

df.head()

        date   T2M
0 2023-01-01  22.1
1 2023-01-02  21.8

In [43]:
from aidweather import PowerClient
from aidweather.utils import ensure_date_column

client = PowerClient()
df = client.get_point_data(
    lat=-23.55, lon=-46.63, start="2023-01-01", end="2023-01-31", params=["T2M"]
)

# df has a DatetimeIndex — convert to a plain column:
df_flat = ensure_date_column(df)

print(df_flat.columns.tolist())  # ["date", "T2M", ...]

['T2M', 'date']

## Bonus: AidWeather ENVIRONMENT Variables

In [44]:
import logging
import os
import tempfile
from pathlib import Path

import aidweather
from aidweather import PowerClient, cfg

In [45]:
# ==============================================================================
# 1. Configure aidweather Environment Variables
# ==============================================================================
# Define custom directory paths for SQLite caching and file logs
custom_cache_dir = Path(tempfile.gettempdir()) / "notebook_aidweather_cache"
custom_log_dir = Path(tempfile.gettempdir()) / "notebook_aidweather_logs"

os.environ["AIDWEATHER_CACHE_DIR"] = str(custom_cache_dir)
os.environ["AIDWEATHER_LOG_DIR"] = str(custom_log_dir)

# Test suite execution flags (used by pytest / smoke runners)
os.environ["AIDWEATHER_RUN_LIVE_TESTS"] = "1"
os.environ["AIDWEATHER_RUN_WHEEL_SMOKE"] = "0"

print("=== Environment Variables Configured ===")
print(f"AIDWEATHER_CACHE_DIR      : {os.environ['AIDWEATHER_CACHE_DIR']}")
print(f"AIDWEATHER_LOG_DIR        : {os.environ['AIDWEATHER_LOG_DIR']}")
print(f"AIDWEATHER_RUN_LIVE_TESTS  : {os.environ['AIDWEATHER_RUN_LIVE_TESTS']}")
print(f"AIDWEATHER_RUN_WHEEL_SMOKE : {os.environ['AIDWEATHER_RUN_WHEEL_SMOKE']}\n")

=== Environment Variables Configured ===
AIDWEATHER_CACHE_DIR      : /tmp/notebook_aidweather_cache
AIDWEATHER_LOG_DIR        : /tmp/notebook_aidweather_logs
AIDWEATHER_RUN_LIVE_TESTS  : 1
AIDWEATHER_RUN_WHEEL_SMOKE : 0

In [46]:
# ==============================================================================
# 2. Inspect Resolved Configuration & Enable File Logging
# ==============================================================================
cache_info = cfg.cache_config()
log_info = cfg.logging_config()

print("=== Resolved System Paths ===")
print(f"Effective Cache Directory : {cache_info['path']}")
print(f"Effective Log File Path   : {log_info['filename']}\n")

=== Resolved System Paths ===
Effective Cache Directory : /tmp/notebook_aidweather_cache
Effective Log File Path   : /tmp/notebook_aidweather_logs/aidweather.log

In [ ]:
# Enable file logging and write an initialization log entry
cfg.set("logging_config.enabled", True)
aidweather._configure_file_logging()
logger = logging.getLogger("aidweather")
logger.info("Notebook cell initialized with environment variable overrides.")

2026-07-17 15:28:49,159 aidweather INFO Notebook cell initialized with environment variable overrides.

In [48]:
# ==============================================================================
# 3. Fetch Data via PowerClient (Uses Custom AIDWEATHER_CACHE_DIR)
# ==============================================================================
client = PowerClient(temporal_api="daily")

df = client.get_point_data(
    lat=-23.55,
    lon=-46.63,
    start="2023-01-01",
    end="2023-01-05",
    params=["T2M", "PRECTOTCORR"],
)

# Flush handlers to write log entries to disk
for handler in logger.handlers:
    handler.flush()

In [49]:
# ==============================================================================
# 4. Verify Storage Artifacts Created in Environment-Specified Paths
# ==============================================================================
cache_db_path = custom_cache_dir / "aidweather_cache.db"
log_file_path = custom_log_dir / "aidweather.log"

print("=== Data Preview ===")
print(df.head())

print("\n=== Storage Artifact Verification ===")
print(
    f"SQLite Cache Created : {cache_db_path.exists()} → ({cache_db_path.resolve()})"
)
print(
    f"Log File Created     : {log_file_path.exists()} → ({log_file_path.resolve()})"
)

if log_file_path.exists():
    print("\n=== Log File Content ===")
    print(log_file_path.read_text().strip())

=== Data Preview ===
              T2M  PRECTOTCORR
date
2023-01-01  22.35         1.85
2023-01-02  22.91         1.26
2023-01-03  22.61         6.21
2023-01-04  21.36        33.93
2023-01-05  18.27        11.71

=== Storage Artifact Verification ===
SQLite Cache Created : True → (/tmp/notebook_aidweather_cache/aidweather_cache.db)
Log File Created     : True → (/tmp/notebook_aidweather_logs/aidweather.log)

=== Log File Content ===
2026-07-17 15:28:49,159 aidweather INFO Notebook cell initialized with environment variable overrides.
2026-07-17 15:28:59,145 aidweather.client INFO Retrieved full date range from cache for key v1_8e63d252c42cc530ad03f8fbbb3a36aa025a0c2bafb4196e3d45424bca252c16.